import { render } from "@react-email/components";
import nodemailer from "nodemailer";
import { Resend } from "resend";
import { BaseEmailTemplate } from "./templates/base";

export function resolveEmailEnvironment(rawEnv: Record<string, string | undefined> = process.env) {
  return {
    from: rawEnv.EMAIL_FROM ?? "Devstack <noreply@example.com>",
    mailpitHost: rawEnv.MAILPIT_HOST ?? "127.0.0.1",
    mailpitPort: Number(rawEnv.MAILPIT_PORT ?? "1025"),
    resendApiKey: rawEnv.RESEND_API_KEY,
  };
}

export async function sendEmail(input: {
  html?: string;
  subject: string;
  text?: string;
  to: string | string[];
}) {
  const environment = resolveEmailEnvironment();
  const to = Array.isArray(input.to) ? input.to : [input.to];
  const html =
    input.html ??
    (await render(
      <BaseEmailTemplate
        preview={input.subject}
        subtitle="Generated by @compozy/devstack"
        title={input.subject}
      />
    ));

  if (environment.resendApiKey) {
    const resend = new Resend(environment.resendApiKey);
    await resend.emails.send({
      from: environment.from,
      html,
      subject: input.subject,
      text: input.text ?? input.subject,
      to,
    });
    return;
  }

  const transporter = nodemailer.createTransport({
    host: environment.mailpitHost,
    port: environment.mailpitPort,
    secure: false,
  });

  await transporter.sendMail({
    from: environment.from,
    html,
    subject: input.subject,
    text: input.text ?? input.subject,
    to,
  });
}
